### ISSUE TITLE
workflow update

### ISSUE THREAD

**Issue by cta0930** [DhanushNehru/tryhackme-badge-action-workflow#1]
Thank you for the valuable tool to get the TryHackMe badge added! I had to update a couple things to get it to work fully and thought I'd drop that in here for others who may want to use it:

Small changes I made apply only to adding the Config Git Identity in addition to ensuring the repo action settings include read/write permissions.

name: Update TryHackMe Badge

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure Git Identity
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"

    - name: Fetch TryHackMe Badge
      uses: DhanushNehru/tryhackme-badge-action-workflow@v1.0
      with:
        image_path: './assets/tryhackme-badge.png'
        username: '.redacted'
        user_id: 'redacted'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

**Comment by DhanushNehru** [comment]
Thanks for adding, if you want to contribute to this repository you can raise a pull request @cta0930
